### ISSUE TITLE
Implement Elder promotion/demotion

### ISSUE THREAD

**Issue by fizyk20** [maidsafe/sn_routing#1835]
- Only the `ELDERS_SIZE` oldest Adults should become Elders.
- Check personae of the members on churn events and promote/demote as needed.
- Change the split logic to count both Elders and Adults in checking whether both sides of the split will have enough nodes
  - Feature-gate lower `ELDERS_SIZE` and `SAFE_SECTION_SIZE` for mock network tests
- Change the logic of tests to allow some nodes to be stuck in the Adult state - currently the tests expect all nodes to end up being Elders.

- [x] https://github.com/maidsafe/routing/pull/1929 initial implementation
- [x] https://github.com/maidsafe/routing/issues/1963 Do not supress parsec prune when relocation is in progress
- [x] https://github.com/maidsafe/routing/issues/1945 make sure Adult can trust updates
- [x] https://github.com/maidsafe/routing/issues/1950 clean up NodeAdded/Lost
- [x] Make sure NodeApproval message can be trusted https://github.com/maidsafe/routing/issues/2022
- [ ] https://github.com/maidsafe/routing/issues/2021 Make sure the RebootStrap/Join response can be trusted so relocating node is not sent toward nodes that were not trusted 
- [ ] ~~Decide if https://github.com/maidsafe/routing/issues/1952 needs fixing and fix it~~ Not needed for this task, will be handled separately.
- [x] https://github.com/maidsafe/routing/issues/1953 Treat infant differently for split etc...

**Comment by madadam** [comment]
This is already implemented apart from the bootstrap response trust issue which doesn't seem to be related much. Will tackle that one separately. Closing.
