### ISSUE TITLE
Remove parsec (meta issue)

### ISSUE THREAD

**Issue by madadam** [maidsafe/sn_routing#2117]
This is a meta issue which gathers all the individual tasks that are needed to remove parsec from routing.

TODO: add and link all the individual issues

- [x] Replace parsec DKG with the BLS-DKG crate (#2107 )
- [x] Make every piece of data in `SharedState` individually signed (#2110)
- [ ] Implement `SharedState` merge operation (#2118)
- [x] Enforce that all mutations to `SharedState` are approved by the section (#2119)
- [ ] Make `SharedState` into CRDT / semilattice (#2120)
- [x] Implement message-based voting (parsec-less voting) (#2121)
- [x] Improve message signature accumulation to not require synchronization via parsec (#2122)
- [x] Remove `section_version` from `SectionMembers` and `MemberInfo` (#2088)
- [x] Make relocation independent on the order of churn events (#2078)
- [x] Remove `churn_event_backlog` from `SharedState` (#2123)
- [x] Remove `relocate_queue` from `SharedState` / overhaul relocation (#2125)
- [x] Remove "relocation cool-down period" / remove `RelocatePrepare` event (#2124)
- [x] Overhaul node promotion / remove `Genesis` event (#2126)
- [x] Change `NeighbourInfo` sending and receiving to not require accumulation (#2127)
- [x] Move neighbour section info updates out of parsec / remove `NeighbourInfo` event
- [x] Move section key updates out of parsec / remove `TheirKey` event
- [x] Move section knowledge updates out of parsec / remove `TheirKnowledge` event
- [x] Move relocations out of parsec / remove `Relocate` event
- [x] Move member churn out of parsec / remove `Online` and `Offline` events
- [x] Move elder churn out of parsec / remove `SectionInfo` event
- [x] Actually remove parsec

**Comment by madadam** [comment]
Parsec is already removed, even though the CRDT-fication of `SharedState` isn't done yet. It's a separate task that's currently ongoing. Keeping those issues open, but closing this one.
